openapi: 3.0.0
servers:
    # Added by API Auto Mocking Plugin
    - description: SwaggerHub API Auto Mocking
      url: https://virtserver.swaggerhub.com/XB0129_1/ClassificationAPI/1.0
    - url: https://excel.sonzea.mx/api
info:
    title: SONZEA CLASSIFICATION API
    description: An API to handle CRUD operations for user custom category templates
    version: '1.0'
security:
    - OAuth2: []
paths:
    /customCategoryTemplates:
        post:
            summary: Create a custom category template
            description: Add a new custom category template for a user
            operationId: createCustomCategoryTemplate
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CustomCategoryTemplate'
            responses:
                '201':
                    description: Created custom category template
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomCategoryTemplate'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
        get:
          summary: Retrieve custom category templates for a user
          description: Get all custom category templates for a user by user ID
          operationId: getCustomCategoryTemplatesByUser
          parameters:
            - name: templateUserID
              in: query
              description: ID of the template owner
              required: false
              schema:
                type: string
          responses:
            '200':
              description: A list of custom category templates
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/CustomCategoryTemplate'
            '400':
              description: Bad request
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
            '404':
              description: User not found

    /customCategoryTemplates/{templateID}:
        get:
          summary: Retrieve custom category templates by ID
          description: Get custom category templates by ID
          operationId: getCustomCategoryTemplatesById
          parameters:
            - name: templateID
              in: path
              description: Custom category template ID to retrieve
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Custom category template found
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CustomCategoryTemplate'
            '400':
              description: Bad request
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
            '404':
              description: Custom category template not found
        put:
            summary: Update a custom category template
            description: Update a specific custom category template by ID
            operationId: updateCustomCategoryTemplate
            parameters:
                - name: templateID
                  in: path
                  description: Custom category template ID to update
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CustomCategoryTemplate'
            responses:
                '200':
                    description: Updated custom category template
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomCategoryTemplate'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '404':
                    description: Custom category template not found

        delete:
            summary: Delete a custom category template
            description: Delete a specific custom category template by ID
            operationId: deleteCustomCategoryTemplate
            parameters:
                - name: templateID
                  in: path
                  description: Custom category template ID to delete
                  required: true
                  schema:
                      type: string
            responses:
                '204':
                    description: Custom category template deleted
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '404':
                    description: Custom category template not found
    /userinfo:
        get:
            summary: Retrieve user information
            description: Get user information based on the Userinfo interface
            operationId: getUserInfo
            responses:
                '200':
                    description: A Userinfo object
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Userinfo'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '404':
                    description: User not found
    /classify:
        post:
            summary: Classify individual records
            description: Classify each record in the provided list of records using a preset or custom template
            operationId: classifyRecords
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                templateID:
                                    type: string
                                    description: The custom template ID to use for classification (optional)
                                records:
                                    type: array
                                    items:
                                        type: string
                                    description: The list of records to classify
            responses:
                '200':
                    description: Classified records
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    message:
                                        type: string
                                    classifiedRecords:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                record:
                                                    type: string
                                                primaryCategory:
                                                    type: string
                                                secondaryCategory:
                                                    type: string
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '402':
                    description: Payment required
                '404':
                    description: User or template not found
    /batchClassify:
        post:
            summary: Classify records in a batch
            description: Classify multiple records in a batch using a preset or custom template
            operationId: batchClassifyRecords
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                templateID:
                                    type: string
                                    description: The custom template ID to use for classification (optional)
                                records:
                                    type: array
                                    items:
                                        type: string
                                    description: The list of records to classify
            responses:
                '200':
                    description: Classified records in a batch
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    message:
                                        type: string
                                    classifiedRecords:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                record:
                                                    type: string
                                                primaryCategory:
                                                    type: string
                                                secondaryCategory:
                                                    type: string
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                '402':
                    description: Payment required
                '404':
                    description: User or template not found
components:
    securitySchemes:
        OAuth2:
            type: oauth2
            flows:
                authorizationCode:
                    authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
                    tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
                    scopes:
                        https://office.sonzea.mx/fff3d687-7456-4966-980b-1cdbaec05c64/user_impersonation: access as user
    schemas:
        CustomCategoryTemplate:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                userID:
                    type: string
                    description: owner of the category template
                childrenNode:
                    type: array
                    items:
                        $ref: '#/components/schemas/ChildrenNode'
        ChildrenNode:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                leafNode:
                    type: array
                    items:
                        $ref: '#/components/schemas/LeafNode'
        LeafNode:
            type: object
            properties:
                id:
                    type: string
                name:
                    type: string
                alias:
                    type: array
                    items:
                        type: string
                feature:
                    type: string
                customize_feature:
                    type: string
        UserSettings:
            type: object
            properties:
                userID:
                    type: string
                customCategoryTemplates:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: string
                            name:
                                type: string
                            categories:
                                type: array
                                items:
                                    $ref: '#/components/schemas/CustomCategoryTemplate'
                language:
                    type: string
                dateFormat:
                    type: string
                currencyUnit:
                    type: string
                displaySettings:
                    type: object
                quickClassificationOptions:
                    type: array
                    items:
                        type: string
                dataImportExportFormat:
                    type: string
                apiCallFrequencyLimit:
                    type: integer
        Subscription:
            type: object
            properties:
                id:
                    type: string
                object:
                    type: string
                application:
                    type: string
                billing_cycle_anchor:
                    type: integer
                created:
                    type: integer
                current_period_end:
                    type: integer
                current_period_start:
                    type: integer
                description:
                    type: string
                trial_start:
                    type: integer
                trial_end:
                    type: integer
                status:
                    type: string
        Userinfo:
            type: object
            properties:
                id:
                    type: string
                object:
                    type: string
                email:
                    type: string
                userID:
                    type: string
                first_name:
                    type: string
                    nullable: true
                last_name:
                    type: string
                    nullable: true
                created:
                    type: integer
                    nullable: true
                display_name:
                    type: string
                    nullable: true
                usage:
                    type: integer
                subscription:
                    type: array
                    items:
                        $ref: '#/components/schemas/Subscription'
                userSettings:
                    $ref: '#/components/schemas/UserSettings'
